prefix = ["fish", "-c"]
store = "1M"

[[watch]]
files = [ '**/*' ]
exclude = [ '.*/**', '*.toml' ]
run = "neofetch"

# [[menu]]
# key = "n"
# run = "neofetch"
#
# [[menu]]
# key = "a"
# run = [ "echo 'Hello, World!'", "ls" ]
