shell = "fish"
store = "1M"

[[watch]]
files = [ '**/*' ]
exclude = [ '.*/**', '*.toml', '*.log' ]
run = "neofetch"
log = "log.log"

# [[menu]]
# key = "n"
# run = "neofetch"
#
# [[menu]]
# key = "a"
# run = [ "echo 'Hello, World!'", "ls" ]
